### ISSUE TITLE
Question about dequantization

### ISSUE THREAD

**Issue by cviviers** [BorealisAI/noise_flow#12]
Hi Abdelrahman,

Very interesting work, thank you for sharing the repo.
I was wondering whether you dequantize the clean image and noise when training noise flow? I couldn't find anything in the code.

Thanks in advance for your feedback.

**Comment by AbdoKamel** [comment]
Hi Chris,

The clean and noisy images in the dataset are floating point numbers in [0, 1], and so the noise. Hope this helps. Thanks for your question.

**Comment by cviviers** [comment]
Yes. Thanks a lot!
