### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by arcchang1236** [BorealisAI/noise_flow#2]
Hello, thanks for the great work of noise modeling.
I want to run your code but get the following error:

FileNotFoundError: [Errno 2] File b'/home/arc/_Code/fourier_flows/experiments/sidd/S6G4/vars.txt' does not exist: b'/home/arc/_Code/fourier_flows/experiments/sidd/S6G4/vars.txt'

I download SIDD_Medium_RAW for training and I think whether other preprocessing steps I should do on the dataset to get VARIANCE_RAW?

**Comment by AbdoKamel** [comment]
Hello!

Thank you for pointing this out. This is a file that was used for variable initialization during development and is no longer needed. The error should be fixed now.

Also, you don't need to do any preprocessing on SIDD to start the training.

**Comment by arcchang1236** [comment]
Thanks a lot. It works without error now.
