### ISSUE TITLE
How to adapt your code into another dataset

### ISSUE THREAD

**Issue by Vandermode** [BorealisAI/noise_flow#6]
Hi, I was wondering how to adapt you code to another dataset for training, e.g. SID dataset [1]

[1] Learning to see in the dark

**Comment by AbdoKamel** [comment]
This will require modifying the data loading code (classes ImageLoader, PatchSampler, etc.) or using your own data loading code.

**Comment by Vandermode** [comment]
Hi, thanks for the reply. I have adapted your method into the SID dataset
