### ISSUE TITLE
TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by sniklaus** [BorealisAI/noise_flow#7]
Thank you for sharing your implementation!

It seems like the server hosting the SIDD dataset is down, or is it just me?

**Comment by sniklaus** [comment]
I downloaded the SIDD from the mirror that they provide on their website: https://www.eecs.yorku.ca/~kamel/sidd/dataset.php

**Comment by Qirui-Y** [comment]
Where can I get the ftp username and password from?

> I downloaded the SIDD from the mirror that they provide on their website: https://www.eecs.yorku.ca/~kamel/sidd/dataset.php
